### ISSUE TITLE
Avoid using eval()

### ISSUE THREAD

**Issue by LuckyDams** [perfecto25/dictor#1]
Hi,

Really enjoy this project, great idea !
But using eval() to get return value (re)formatted lookup syntax is a no go for me. This is prone to malicious code execution and a major security concern.

Would be nice to rework this part and using solutions discussed here: https://stackoverflow.com/a/52260663

This is just my opinion and a suggestion, no criticism from me.
Again, dictor is a simple but great idea !

**Comment by perfecto25** [comment]
very valid point, ill see if I can make it work w /o eval

**Comment by perfecto25** [comment]
Eval removed from newest version (0.1.1)
see README Release Notes for all updates to latest package.
