### ISSUE TITLE
Any direct way to use keypath for list of dictionaries?

### ISSUE THREAD

**Issue by sameer-j** [perfecto25/dictor#17]
Example:
maindict = 
```
{
	"components": [
		{
			"name": "comp1",
			"value": "value1"
		},
		{
			"name": "comp2",
			"value": "value2"
		}
	]
}
```

I would like to get a result like this: ["comp1", "comp2"]

Any way to achieve this?

**Comment by perfecto25** [comment]
this looks like you want a "search" function, to search for anything with "name". 

the only way currently to do this, is like this,

```
for key in dictor(maindict, 'components'): print dictor(key, 'name')

## output 
comp1
comp2
```

I will see if I can add this a Search function

**Comment by sameer-j** [comment]
Yeah, we can call it search. But not through all the levels.
Eg if the data is:
```
{
	"components": [
		{
			"name": "comp1",
			"value": "value1",
                        "subcomponent": {
                               "name": "subcomp1"
                         }
		},
		{
			"name": "comp2",
			"value": "value2",
                         "subcomponent": {
                               "name": "subcomp1"
                         }
		}
	]
}
```
I wish to something like components.name and get ["comp1", "comp"] and don't need the subcomponent name

**Comment by perfecto25** [comment]
thanks Sameer, would something like this work, passing a Search flag?

```
print dictor(data, "components.name",  search=True)
>> ['comp1', 'comp2']
```

**Comment by perfecto25** [comment]
latest version has search flag to search keys
