### ISSUE TITLE
Bringing back the ability to escape the path separator

### ISSUE THREAD

**Issue by andrewkowalik** [perfecto25/dictor#26]
It looks like this commit https://github.com/perfecto25/dictor/commit/20ad292e41058b0bb180bf5bf36c32395ee375cb removed the ability to escape the path separator. I don't believe the commit change really matched the original use case of escaping. Would y'all be ok if we introduced that feature back?

**Comment by perfecto25** [comment]
what do you mean 'escape path separator'?

can you give an example

**Comment by perfecto25** [comment]
this is now added in v 0.1.9

**Comment by andrewkowalik** [comment]
@perfecto25 Great this seems to do the trick. For history, the use case here is when a key contains the path separator that is already established and the key cannot be modified. 

Thanks!
