### ISSUE TITLE
Handle search key scenario if the path the user passed doesn't exist

### ISSUE THREAD

**Issue by karthikkalasani** [perfecto25/dictor#31]
Search for a specific key is throwing error if path doesn't exists and if return None
https://github.com/perfecto25/dictor/blob/master/dictor/__init__.py#L139-L142

The above code in the line 140 is returning None if the full path doesn't exists, later the same none is passed to line 142 and that is throwing NoneType exception.

1) Can we just return the default value if that path or search key doesn't exist?

@perfecto25

**Comment by perfecto25** [comment]
fixed in new release

**Comment by karthikkalasani** [comment]
Great!Thanks for that quick fix
