### ISSUE TITLE
Empty string value treated as missing value

### ISSUE THREAD

**Issue by jpsutton** [perfecto25/dictor#37]
`dictor()`'s current implementation treats both empty values and missing values as situations where the `default` value is returned. This can be seen from the following lines:

```
    if val is None or val == "":
        return default
```

I don't believe this is a reasonable default behavior, as an object may have a key with an empty string for a value, which may be a distinct desired state from either a missing key or even a value of `None`.

**Comment by dawid-szaniawski** [comment]
@perfecto25 from my perspective, it also looks like an error. The fix:
https://github.com/perfecto25/dictor/pull/38

**Comment by perfecto25** [comment]
this will be fixed in next release

**Comment by perfecto25** [comment]
adding additional logic to flatten out nested dict structures for search lookups
