### ISSUE TITLE
Numeric keys handling

### ISSUE THREAD

**Issue by tdentafix** [perfecto25/dictor#7]
Hello,

I noticed that dictor does not seem to support cases when dictionary keys are strings composed only of numbers, e.g. :

```
{
      "1200": "banana",
      "2000": "apple"
}
```

Am I doing something wrong ?

Thanks in advance.

**Comment by perfecto25** [comment]
thanks for the bug submit, this is now fixed in latest version, 0.1.3

**Comment by tdentafix** [comment]
Thanks a lot for the fix ! Dictor is an amazing tool, keep up the good work !
